/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import AccesoDatosORM.*;
import Administracion.*;
import Validaciones.Validaciones;
import java.time.LocalTime;
import javax.swing.border.Border;

/**
 *
 * @author Joan
 */
public class VentanaLogin extends javax.swing.JFrame {

    Validaciones validaciones = new Validaciones();
    AdaptadorSucursalControlador controladorSucursal = new AdaptadorSucursalControlador();
    AdaptadorEmpleadoControlador controladorEmpleado = new AdaptadorEmpleadoControlador();
    AdaptadorCategoriaControlador controladorCategoria = new AdaptadorCategoriaControlador();
    AdaptadorItemControlador controladorItem = new AdaptadorItemControlador();
    AdaptadorClienteControlador controladorCliente = new AdaptadorClienteControlador();
    AdaptadorFacturaControlador controladorFactura = new AdaptadorFacturaControlador();
    AdaptadorFacturaItemControlador controladorFacturaItem = new AdaptadorFacturaItemControlador();
    AdaptadorPedidoControlador controladorPedido = new AdaptadorPedidoControlador();
    
    /**
     * Creates new form GUILogin
     */
    public VentanaLogin() {
        super("Bienvenido a la Pizzería Cheers");
        initComponents();
        setLocationRelativeTo(null);
        
        // Creando sucursal
        Sucursal nuevaSucursal = new Sucursal("Cheers Cali", "Calle 20", "2945423");
        controladorSucursal.crearSucursal(nuevaSucursal);
        
        // Creando empleados (meseros) asociados a sucursal
        Empleado mesero_uno = new Empleado("11440927462", "CC", "Vin" , "Diesel",  "Calle 10", "3204542393", "Mesero", "contraseña", LocalTime.of(8, 0), LocalTime.of(16, 0), null, nuevaSucursal);
        
        Empleado mesero_dos = new Empleado("1144150569", "CC", "Paul" , "Walker",  "Calle 20", "3104953921", "Mesero", "contraseña", LocalTime.of(8, 0), LocalTime.of(16, 0), null, nuevaSucursal);
        
        controladorEmpleado.crearEmpleado(mesero_uno);
        controladorEmpleado.crearEmpleado(mesero_dos);
        
        // Obteniendo mesero registrado
        Empleado mesero_uno_back = controladorEmpleado.obtenerEmpleado("1144150569");
        System.out.println(mesero_uno_back.toString());
        
        // Creando categoria
        Categoria nuevaCategoria = new Categoria("Sopas");
        controladorCategoria.crearCategoria(nuevaCategoria);
        
        // Creando Item asociado a categoria
        Item item1 = new Item("Sopa de pastas", "Sopa hecha con pastas", 3000, null, nuevaCategoria);
        controladorItem.crearItem(item1);
        
        Item item2 = new Item("Sopa de carne", "Sopa con carne cocinada", 3000, null, nuevaCategoria);
        controladorItem.crearItem(item2);
        
        // Creando cliente
        Cliente nuevoCliente = new Cliente("1110230459", "Luis", "Molano", "Calle 15", "3495432", "3184594323", "luis.molano@gmail.com");
        controladorCliente.crearCliente(nuevoCliente);
        
        // Creando empleado (cajero)
        Empleado cajero1 = new Empleado("1120349584", "CC", "Victor", "Garcia", "Calle 19", "3214596843", "Cajero", "contraseña", LocalTime.of(8, 0), LocalTime.of(16, 0), null, nuevaSucursal);
        controladorEmpleado.crearEmpleado(cajero1);
        
        // Creando Factura
        Factura nuevaFactura = new Factura("Efectivo", LocalTime.of(10, 0), 5000, 2000, 0, cajero1, nuevoCliente);
        controladorFactura.crearFactura(nuevaFactura);
        
        // Agregando Items a la factura
        
        Factura_Item ingresoItem1 = new Factura_Item(1L, 1L);
        Factura_Item ingresoItem2 = new Factura_Item(1L, 2L);
        
        controladorFacturaItem.crearFacturaItem(ingresoItem1);
        controladorFacturaItem.crearFacturaItem(ingresoItem2);
        
        // Creando Pedido
        Pedido nuevoPedido = new Pedido("A domicilio", LocalTime.of(9, 10), LocalTime.of(9, 15), nuevoCliente, nuevaSucursal);
        controladorPedido.crearPedido(nuevoPedido);
    }
    
    public void limpiarCampos(){
        setLocationRelativeTo(null);
        tfUser.setText("");
        tfPasswd.setText("");        
        tfUser.requestFocus();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        tfUser = new javax.swing.JTextField();
        tfPasswd = new javax.swing.JPasswordField();
        lLogo = new javax.swing.JLabel();
        bLogin = new javax.swing.JButton();
        lInfoIngreso = new javax.swing.JLabel();
        lUser = new javax.swing.JLabel();
        lPass = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        panelPrincipal.setBackground(new java.awt.Color(89, 30, 27));

        tfUser.setFont(new java.awt.Font("Eras Medium ITC", 0, 16)); // NOI18N
        tfUser.setText("username");
        tfUser.setPreferredSize(new java.awt.Dimension(53, 30));

        tfPasswd.setFont(new java.awt.Font("Eras Medium ITC", 0, 16)); // NOI18N
        tfPasswd.setText("jPasswordField1");

        lLogo.setBackground(new java.awt.Color(89, 30, 27));
        lLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N

        bLogin.setFont(new java.awt.Font("Eras Medium ITC", 0, 16)); // NOI18N
        bLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bLogin.png"))); // NOI18N
        bLogin.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bLoginPR.png"))); // NOI18N
        bLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLoginActionPerformed(evt);
            }
        });

        lInfoIngreso.setFont(new java.awt.Font("Eras Medium ITC", 0, 16)); // NOI18N
        lInfoIngreso.setForeground(new java.awt.Color(255, 255, 255));
        lInfoIngreso.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lInfoIngreso.setText("Por favor, ingrese sus datos para iniciar sesión");

        lUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user.png"))); // NOI18N

        lPass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/lock.png"))); // NOI18N

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lInfoIngreso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addComponent(lLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelPrincipalLayout.createSequentialGroup()
                                .addComponent(lUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(tfUser, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelPrincipalLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(bLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelPrincipalLayout.createSequentialGroup()
                                .addComponent(lPass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(tfPasswd, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(100, 100, 100))
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincipalLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lUser, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfUser, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfPasswd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lPass, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(bLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(lLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32)
                .addComponent(lInfoIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLoginActionPerformed
        
        VentanaPrincipal ventanaPpal = new VentanaPrincipal(this);
        ventanaPpal.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_bLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bLogin;
    private javax.swing.JLabel lInfoIngreso;
    private javax.swing.JLabel lLogo;
    private javax.swing.JLabel lPass;
    private javax.swing.JLabel lUser;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JPasswordField tfPasswd;
    private javax.swing.JTextField tfUser;
    // End of variables declaration//GEN-END:variables
}
