/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.GUIFacturacionYPagos;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import AccesoDatosORM.AdaptadorPedidoControlador;
import Administracion.Pedido;
import java.math.BigInteger;
import java.util.ArrayList;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author invitado
 */
public class VentanaPedidosAPagar extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPedidosEntregados
     */
    
    JFrame ventanaAnterior;
    AdaptadorPedidoControlador controladorPedido = new AdaptadorPedidoControlador();
    TableRowSorter trsFiltro;
    
    public VentanaPedidosAPagar(JFrame anterior) {
        super("Pago de pedidos");
        initComponents();
        
        this.ventanaAnterior = anterior;
        setLocationRelativeTo(null); 
        
        llenarTablaPedidos();
        
        trsFiltro = new TableRowSorter(tablaPedidos.getModel());
        tablaPedidos.setRowSorter(trsFiltro);

    }
    
    public ArrayList<Pedido> pedidosNoPagos(ArrayList<BigInteger> numeroPedidos){
        
        ArrayList<Pedido> pedidos = new ArrayList<>();
        Pedido pedido = new Pedido();
        
        for(int i = 0; i < numeroPedidos.size(); i++){
            
            pedido = controladorPedido.obtenerPedido((Long) numeroPedidos.get(i).longValue());
            pedidos.add(pedido);          
        }
        
        return pedidos;
                
    }
    
    public void llenarTablaPedidos(){
        
        DefaultTableModel modelo = (DefaultTableModel) tablaPedidos.getModel();
        modelo.setRowCount(0);
        
        for(int i = 0; i < modelo.getRowCount(); i++){
            
            modelo.removeRow(i);
            i -= 1;
        }
        
        ArrayList<BigInteger> numeroPedidos = controladorPedido.obtenerPedidosNoPagos();
        ArrayList<Pedido> pedidos = pedidosNoPagos(numeroPedidos);
        
        if(pedidos != null){
        
            for(int i = 0; i < pedidos.size(); i++){
                
                Object[] fila = new Object[3];
                
                fila[0] = pedidos.get(i).getNumero();
                fila[1] = pedidos.get(i).getCliente().getId();
                fila[2] = pedidos.get(i).getTotal();
                
                modelo.addRow(fila);
            
            }
            
            tablaPedidos.setModel(modelo);
        }else{
            JOptionPane.showMessageDialog(null, "No hay pedidos por pagar", "Información", JOptionPane.INFORMATION_MESSAGE);
        }
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        panelInferior = new javax.swing.JPanel();
        bAtras = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaPedidos = new javax.swing.JTable();
        bVerFacturas = new javax.swing.JButton();
        bPagarPedido = new javax.swing.JButton();
        tfFiltroIDCliente = new javax.swing.JTextField();
        lIDCliente = new javax.swing.JLabel();
        tfFiltroCodigo = new javax.swing.JTextField();
        lFiltroCodigo = new javax.swing.JLabel();
        lFiltro = new javax.swing.JLabel();
        lLogo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelPrincipal.setBackground(new java.awt.Color(89, 30, 27));

        panelInferior.setBackground(new java.awt.Color(89, 30, 27));
        panelInferior.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Pedidos por pagar", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Eras Medium ITC", 0, 16), new java.awt.Color(255, 255, 255))); // NOI18N

        bAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bAtras.png"))); // NOI18N
        bAtras.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bAtrasPR.png"))); // NOI18N
        bAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAtrasActionPerformed(evt);
            }
        });

        tablaPedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Código", "ID Cliente", "Precio Neto"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaPedidos);

        bVerFacturas.setText("Ver Facturas");
        bVerFacturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVerFacturasActionPerformed(evt);
            }
        });

        bPagarPedido.setText("Realizar Pago");
        bPagarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPagarPedidoActionPerformed(evt);
            }
        });

        tfFiltroIDCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfFiltroIDClienteKeyReleased(evt);
            }
        });

        lIDCliente.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        lIDCliente.setForeground(new java.awt.Color(255, 255, 255));
        lIDCliente.setText("ID Cliente:");

        tfFiltroCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfFiltroCodigoKeyReleased(evt);
            }
        });

        lFiltroCodigo.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        lFiltroCodigo.setForeground(new java.awt.Color(255, 255, 255));
        lFiltroCodigo.setText("Código:");

        lFiltro.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        lFiltro.setForeground(new java.awt.Color(255, 255, 255));
        lFiltro.setText("Filtrar por:");

        javax.swing.GroupLayout panelInferiorLayout = new javax.swing.GroupLayout(panelInferior);
        panelInferior.setLayout(panelInferiorLayout);
        panelInferiorLayout.setHorizontalGroup(
            panelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInferiorLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(panelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInferiorLayout.createSequentialGroup()
                        .addComponent(bAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(151, 151, 151)
                        .addComponent(bVerFacturas)
                        .addGap(48, 48, 48)
                        .addComponent(bPagarPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelInferiorLayout.createSequentialGroup()
                        .addComponent(lFiltro)
                        .addGap(18, 18, 18)
                        .addComponent(lFiltroCodigo)
                        .addGap(18, 18, 18)
                        .addComponent(tfFiltroCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(lIDCliente)
                        .addGap(18, 18, 18)
                        .addComponent(tfFiltroIDCliente))
                    .addComponent(jScrollPane1))
                .addGap(25, 25, 25))
        );
        panelInferiorLayout.setVerticalGroup(
            panelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInferiorLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(panelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfFiltroIDCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lIDCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tfFiltroCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lFiltroCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(panelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bAtras, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bVerFacturas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bPagarPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(21, 21, 21))
        );

        lLogo.setBackground(new java.awt.Color(89, 30, 27));
        lLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logoPequeno.png"))); // NOI18N
        lLogo.setMaximumSize(new java.awt.Dimension(140, 140));
        lLogo.setMinimumSize(new java.awt.Dimension(140, 140));
        lLogo.setPreferredSize(new java.awt.Dimension(140, 140));

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(panelInferior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGap(248, 248, 248)
                        .addComponent(lLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelInferior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAtrasActionPerformed

        this.dispose();
        ventanaAnterior.setVisible(true);
        
    }//GEN-LAST:event_bAtrasActionPerformed

    private void bVerFacturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVerFacturasActionPerformed

        VentanaGestionFacturas vFacturas = new VentanaGestionFacturas(this);
        vFacturas.setVisible(true);
        this.setVisible(false);        
        
    }//GEN-LAST:event_bVerFacturasActionPerformed

    private void bPagarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPagarPedidoActionPerformed

        
        int filasSeleccionadas = tablaPedidos.getSelectedRowCount();        
             
        
        if(filasSeleccionadas == 1){            
        
            //Mandar información del pedido a esta ventana como parámetro
            
            int filaSeleccionada = tablaPedidos.getSelectedRow();
            
            DefaultTableModel modelo = (DefaultTableModel) tablaPedidos.getModel();
            filaSeleccionada = tablaPedidos.getRowSorter().convertRowIndexToModel(filaSeleccionada);
            
            Long numeroPedido = (Long) modelo.getValueAt(filaSeleccionada, 0);
            
            Pedido pedidoSeleccionado = controladorPedido.obtenerPedido(numeroPedido);
            
            VentanaRegistrarPago ventanaPago = new VentanaRegistrarPago(this, pedidoSeleccionado);
            ventanaPago.setVisible(true);
            this.setVisible(false);
            
        }else{
            JOptionPane.showMessageDialog(null, "Seleccione un pedido", "Error", JOptionPane.INFORMATION_MESSAGE);
        }
        
        
        
    }//GEN-LAST:event_bPagarPedidoActionPerformed

    private void tfFiltroCodigoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfFiltroCodigoKeyReleased
        // TODO add your handling code here:
        int columna = 0;
        
        trsFiltro.setRowFilter(RowFilter.regexFilter(tfFiltroCodigo.getText(), columna));
    }//GEN-LAST:event_tfFiltroCodigoKeyReleased

    private void tfFiltroIDClienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfFiltroIDClienteKeyReleased
        // TODO add your handling code here:
        int columna = 1;
        
        trsFiltro.setRowFilter(RowFilter.regexFilter(tfFiltroIDCliente.getText(), columna));
        
    }//GEN-LAST:event_tfFiltroIDClienteKeyReleased

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPedidosAPagar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPedidosAPagar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPedidosAPagar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPedidosAPagar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPedidosAPagar(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAtras;
    private javax.swing.JButton bPagarPedido;
    private javax.swing.JButton bVerFacturas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lFiltro;
    private javax.swing.JLabel lFiltroCodigo;
    private javax.swing.JLabel lIDCliente;
    private javax.swing.JLabel lLogo;
    private javax.swing.JPanel panelInferior;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JTable tablaPedidos;
    private javax.swing.JTextField tfFiltroCodigo;
    private javax.swing.JTextField tfFiltroIDCliente;
    // End of variables declaration//GEN-END:variables
}
